### ISSUE TITLE
Disable native popup on icon change

### ISSUE THREAD

**Issue by dhubenko** [kyubuns/AppIconChangerUnity#11]
Icon changing in runtime is more a marketing feature than user setting.

On android we can change icon via google console, but on iOS there is no other way except making new release.

This plugin is a very good try to solve our problem. It works great. The only problem - it opens native popup with "ok" button on every icon change. Thats not user friendly...

Is there any chance to implement this solutions to disable that native popup?
https://stackoverflow.com/questions/43356570/alternate-icon-in-ios-10-3-avoid-notification-dialog-for-icon-change

**Comment by kyubuns** [comment]
I didn't know there was a way to do that!
But I'm not sure if Apple would allow it, so I wouldn't put it in the main branch.
Maybe they're secretly experimenting in other branches...

**Comment by kyubuns** [comment]
It did work.
But I don't know if the implementation of this branch is Apple-approved.
Use at your own risk.
https://github.com/kyubuns/AppIconChangerUnity/tree/disable_popup
