### ISSUE TITLE
[Question] What is the relationship between alternate setting and the primary one that Unity provided?

### ISSUE THREAD

**Issue by CodeMasterYi** [kyubuns/AppIconChangerUnity#5]
As the title, I would like to know what is the relationship between alternate setting and the primary one that Unity provided is?
Long for reply.

**Comment by kyubuns** [comment]
This is about how iOS (Xcode) works.

All iOS applications have a default icon.
The primary one that Unity provided specifies the default icon.
(This is the oldest and most popular method of designating icons.)

"AlternateIcons" is a feature added in iOS10.
It allows you to change the default icon to another icon.

The application initially uses the default icon.
You can change to different app icons by using AlternateIcons.
Of course, you can also revert to the default icon.
