### ISSUE TITLE
Gray icon on device

### ISSUE THREAD

**Issue by Micro4lik** [kyubuns/AppIconChangerUnity#6]
Why alternative icon is gray on mobile, but on app store is correct?
![IMG_1411](https://github.com/kyubuns/AppIconChangerUnity/assets/34659658/ef15105e-0183-4f50-a7d0-1de789fef29a)

**Comment by kyubuns** [comment]
It seems that someone else had the same problem without my knowledge.
https://qiita.com/kyorokyoro/items/98d0410ada0a14535bb3

Let me ask two additional questions.
- Do you do your builds from the command line?
- It may be a Source image issue. Please send that file as is to kyubuns@gmail.com .

**Comment by kyubuns** [comment]
https://github.com/kyubuns/AppIconChangerUnity/releases/tag/v2.2.0
Until we can come up with a better way, we decided to display the warning first.
<img width="422" alt="Screenshot 2023-07-13 at 1 35 28" src="https://github.com/kyubuns/AppIconChangerUnity/assets/961165/8e5cd375-d55f-480e-bcc3-e527b1f51bbb">

**Comment by kyubuns** [comment]
Thanks for the report.
I will close this issue as it is probably the same phenomenon.

I will summarize my conclusion again.
"Auto Generate" does not work correctly when built with the -nographics option. In that case, please use "Manual".
